name: 'Fsharp Custom Action'
description: 'Get the modified directories in a formatted style'
inputs:
  values-to-take:
    description: >
      In order to avoid presenting very old tags at the workflow options, this input let's you
      specify how many tags to take, considering the order starting from the new tags to the
      old tags. If you don't specify this value, it will take all the tags.
    default: '-1'
  workflow-file-name:
    description: >
      Specify the target workflow file name that must live under `.github/workflows/`.
  workflow-yaml-key:
    description: >
      Specify the workflow YAML key that will be updated.
  repo-path:
    description: >
      The path for the checkout repository.
  git-tags:
    description: >
      The tags from the repository ordered from the most recent to the most old.
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    VALUES_TO_TAKE: ${{ inputs.values-to-take }}
    WORKFLOW_FILE_NAME: ${{ inputs.workflow-file-name }}
    WORKFLOW_KEY: ${{ inputs.workflow-yaml-key }}
    REPO_PATH: ${{ inputs.repo_path }}
    GIT_TAGS: ${{ inputs.git-tags }}